#!/usr/bin/env bash

DIR="$HOME/Immagini/sfondi"
BG=background.* #will works?
OPT=fill #default
CONFIG_FILE=$HOME/Immagini/sfondi/.config
main_page() {
    clear
    echo """            ~~~wallpapermenu~~~
        [1] set wallpaper   [2] change settings
        [3] apply           [4] cancel"""
    read -N 1 -s choice
    case $choice in
        1)
            set_wallpaper;;
        2)
            change_settings;;
        3)
            echo $OPT $BG > $CONFIG_FILE;
            apply_settings $OPT $BG;;
        4)
            apply_settings "$(< $CONFIG_FILE)";;
        *)
        main_page;;
    esac


}

set_wallpaper() {
    local r_img=12
    local c_img=40

    list=$(ls $DIR)

    bgs=( ${list} )
    
    n=0
    for i in ${list}; do
        echo "[$n] $i"
        chafa -w 9 -s $r_imgx$c_img $DIR/$i
        let n++
    done

    read -N 1 -s choice

    BG=$DIR/${bgs[$choice]}
#    echo $BG
#    echo "$DIR/${list}"
    main_page
}
change_settings() {
    clear
    echo "[1] fill    [2] center
        [3] max     [4] scale
        [5] tile"
    read -N 1 -s choice
    case $choice in
        1)
            OPT="fill";;
        2)
            OPT="center";;
        3)
            OPT="max";;
        4)
            OPT="scale";;
        5)
            OPT="tile";;
        *)
            change_settings;;
    esac
    main_page
}

apply_settings() {

    feh --no-fehbg --bg-$1 $2
}


if [[ $1 == --no-gui ]]; then
    apply_settings "$(< $CONFIG_FILE)"
elif [[ $1 == --no-cli ]]; then
    apply_settings "$(< $CONFIG_FILE)"
elif [[ $1 == --no-ui ]]; then
    apply_settings "$(< $CONFIG_FILE)"
else
    main_page
fi

