#!/usr/bin/env bash

DIR="$HOME/Immagini/Sfondi"
BG=background.* #will works?
OPT=fill #default
CONFIG_FILE=$HOME/Immagini/Sfondi/.config
main_page() {
    clear
    echo """            ~~~wallpapermenu~~~
        [1] set wallpaper   [2] change settings
        [3] apply           [4] cancel"""
    read -N 1 -s choice
    case $choice in
        1)
            set_wallpaper;;
        2)
            change_settings;;
        3)
            apply_settings $OPT $BG;;
        4)
            apply_settings "$(< $CONFIG_FILE)";;
        *)
        main_page;;
    esac


}

set_wallpaper() {
    local r_img=12
    local c_img=40

    list=$(ls $DIR)

    bgs=( ${list} )

    n=0
    for i in ${list}; do
        echo "[$n] $i"
        chafa -w 9 -s $r_imgx$c_img $DIR/$i
        let n++
    done

    read -N 1 -s choice

    BG=$DIR/${bgs[$choice]}
#    echo $BG
#    echo "$DIR/${list}"
    main_page
}

set_wallpaper() {
    local r_img=22
    local c_img=40
    local focus_color='\033[7m'
    local nc='\033[0m' # No Color
    list=$(ls $DIR)
    bgs=( ${list} )

    wall_focused=0

    while true; do
        clear
        n=0
        paste <( echo ┌┤wallpapermenu├┐ #TODO: swap image and menù will fix the glitch
        for i in ${list}; do
            echo -n "│ "
            if [ $n == $wall_focused ]; then
                echo -n -e $focus_color
            fi
            echo -e "[$n] ${i:0:9}$nc │"
            let n++
        done
        echo └───────────────┘
        while [[ $n -lt $r_img ]]; do #I'll try something better
            echo "                  "
            let n++
        done ) <( chafa -w 9 -s $r_imgx$c_img $DIR/${bgs[$wall_focused]} )
        read -N 1 -s choice
        if [[ $choice = "w" ]] && [[ $wall_focused -gt 0 ]] ; then
            let wall_focused--;
        elif [[ $choice = "s" ]] && [[ $wall_focused -lt $((${#bgs[@]}-1)) ]]; then
            let wall_focused++;
        elif [[ $choice = "e" ]]; then
            BG=$DIR/${bgs[$wall_focused]}; break
        elif [[ $choice -ge 0 ]] && [[ $choice -lt ${#bgs[@]} ]]; then
            BG=$DIR/${bgs[$choice]}; break
        fi
    done
    main_page
}

change_settings() {
    clear
    echo "[1] fill    [2] center
        [3] max     [4] scale
        [5] tile"
    read -N 1 -s choice
    case $choice in
        1)
            OPT="fill";;
        2)
            OPT="center";;
        3)
            OPT="max";;
        4)
            OPT="scale";;
        5)
            OPT="tile";;
        *)
            change_settings;;
    esac
    main_page
}

apply_settings() {
    echo $1 $2 > $CONFIG_FILE

    feh --bg-$1 $2
}


if [[ $1 == --no-gui ]]; then
    apply_settings "$(< $CONFIG_FILE)"
else
    main_page
fi
